### ISSUE TITLE
运行出错：Blas xGEMMBatched launch failed

### ISSUE THREAD

**Issue by Jimmy880** [shenweichen/Bytedance_ICME2019_challenge_baseline#8]
直接运行代码的时候在预测的时候报错，报错代码如下：
```
2019-03-25 20:43:43.763317: E tensorflow/stream_executor/cuda/cuda_blas.cc:652] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_NOT_SUPPORTED
2019-03-25 20:43:43.763384: E tensorflow/stream_executor/cuda/cuda_blas.cc:2574] Internal: failed BLAS call, see log for details
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    pred_ans = model.predict(test_model_input, batch_size=2**14)
  File "/home/wangzhenyu/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1878, in predict
    self, x, batch_size=batch_size, verbose=verbose, steps=steps)
  File "/home/wangzhenyu/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 326, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/wangzhenyu/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "/home/wangzhenyu/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/wangzhenyu/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMMBatched launch failed : a.shape=[131072,9,1], b.shape=[131072,9,1], m=9, n=9, k=1, batch_size=131072
         [[{{node cin/MatMul}} = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](cin/MatMul_1/a, cin/MatMul_1/a)]]
         [[{{node mlp_1/Tensordot/Shape/_377}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_229_mlp_1/Tensordot/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]
```
修改predict的batch_size是可以运行，但是以2**14的batch_size无法运行

**Comment by shenweichen** [comment]
那就用小点的batch_size运行吧~

**Comment by Jimmy880** [comment]
我查了资料好像是cuda版本的问题，原来是9.2的cuda换成9.0就好了

**Comment by shenweichen** [comment]
好的~

**Comment by itxiud2015** [comment]
@Jimmy880 我从9.2的cuda换成9.0的，还是不行，请问你cudnn的版本是？
